version: "3.7"

services:
  # ClickHouse Database
  clickhouse:
    image: clickhouse/clickhouse-server:23.11.1-alpine
    container_name: signoz-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Zookeeper for Kafka
  zookeeper:
    image: bitnami/zookeeper:3.7.1
    container_name: signoz-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami

  # Kafka Message Broker
  kafka:
    image: bitnami/kafka:2.8.1
    container_name: signoz-kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  # OpenTelemetry Collector
  otel-collector:
    image: signoz/signoz-otel-collector:0.88.11
    container_name: signoz-otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      clickhouse:
        condition: service_healthy  # Wait for ClickHouse to be healthy
    environment:
      - LOG_LEVEL=DEBUG
      - SPAN_STORAGE_TYPE=clickhouse
      - CLICKHOUSE_DATABASE=signoz_traces
      - CLICKHOUSE_CONNECTION=http://clickhouse:8123
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://localhost:13133"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Query Service
  query-service:
    image: signoz/query-service:0.38.2
    container_name: signoz-query-service
    ports:
      - "8080:8080"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - JWT_SECRET=signoz_secret_key
    depends_on:
      clickhouse:
        condition: service_healthy  # Wait for ClickHouse to be healthy

  # SigNoz Frontend
  frontend:
    image: signoz/frontend:0.38.2
    container_name: signoz-frontend
    ports:
      - "3301:3301"
    environment:
      - QUERY_SERVICE_URL=http://query-service:8080
    depends_on:
      - query-service

volumes:
  clickhouse_data:
  zookeeper_data:
  kafka_data:
