version: '3.8'
services:
  mediawiki:
    image: mediawiki
    restart: always
    networks:
      - docker_network
    ports:
      - 8080:80
    volumes:
      - ./mediawiki:/var/www/html
    depends_on:
      - database
    environment:
      - MEDIAWIKI_DB_HOST=database
      - MEDIAWIKI_DB_NAME=wiki_db
      - MEDIAWIKI_DB_USER=wikimedia
      - MEDIAWIKI_DB_PASSWORD=wikimedia

  database:
    image: mysql:5.7
    restart: always
    networks:
      - docker_network
    environment:
      MYSQL_DATABASE: wiki_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wikimedia
      MYSQL_PASSWORD: wikimedia
    volumes:
      - ./mediawiki:/var/lib/mysql

networks:
  docker_network:
    driver: bridge

volumes:
  db_data:
