version: "3.7"
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - clickhouse-setup_default

networks:
  clickhouse-setup_default:
    external: true
