version: '3.8'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./db:/db
    depends_on:
      - db
  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./db:/db
    working_dir: /db
    entrypoint: tail -f /dev/null
